// generated by Fast Light User Interface Designer (fluid) version 2.0100

#include "PALESDL_GUI.H"

fltk::Window* mainwind;

fltk::Button* butMemscan;

static void cb_butMemscan(fltk::Button*, void*) {
  set_show_memscan(1);
}

fltk::Button* butCPM;

fltk::Button* butStopemu;

static void cb_butStopemu(fltk::Button*, void*) {
  stop_emu();
}

fltk::Button* butReset;

static void cb_butReset(fltk::Button*, void*) {
  reset_emu();
}

fltk::Button* butROMbuilder;

static void cb_butROMbuilder(fltk::Button*, void*) {
  wndROMbuilder->show();
  update_ROMfiles();
}

fltk::Button* butExit;

static void cb_butExit(fltk::Button*, void*) {
  quit_emu();
}

fltk::Button* butControlMore;

fltk::Button* butHelp;

static void cb_butHelp(fltk::Button*, void*) {
  wndAbout->show();
}

fltk::Button* butStartemu;

static void cb_butStartemu(fltk::Button*, void*) {
  start_emu();
}

fltk::Button* butSSemu;

static void cb_butSSemu(fltk::Button*, void*) {
  single_step_emu();
}

fltk::Button* butRunprogram;

static void cb_butRunprogram(fltk::Button*, void*) {
  pump_string("run\x0d");
  
  //pump_string("run\x0d");
}

fltk::Choice* chcLanguage;

fltk::Choice* chcSpeed;

static void cb_chcSpeed(fltk::Choice* o, void*) {
  set_speed(o->value());
}

fltk::Choice* chcMtype;

static void cb_chcMtype(fltk::Choice* o, void*) {
  set_machine(o->value());
}

fltk::Choice* chcDisplay;

static void cb_chcDisplay(fltk::Choice* o, void*) {
  set_display(o->value());
}

fltk::Button* butDisplayReset;

fltk::CheckButton* chkSysvars;

static void cb_chkSysvars(fltk::CheckButton* o, void*) {
  set_show_sysvars(o->value());
}

fltk::CheckButton* chkMemmap;

static void cb_chkMemmap(fltk::CheckButton* o, void*) {
  set_show_memmap(o->value());
}

fltk::CheckButton* chkStatus;

static void cb_chkStatus(fltk::CheckButton* o, void*) {
  set_show_status(o->value());
}

fltk::Divider* divNumber1;

fltk::MultilineOutput* txtoTapeInfo;

fltk::Output* txtoRevisions;

static void cb_LIST(fltk::Button*, void*) {
  pump_string("list\x0d");
}

fltk::Choice* chcTtype;

static void cb_chcTtype(fltk::Choice* o, void*) {
  set_t_mode(o->value());
}

fltk::Group* grpTapeDirect;

fltk::Button* butTapePlay;

static void cb_butTapePlay(fltk::Button*, void*) {
  force_raw_play();
}

fltk::Button* butTapePause;

static void cb_butTapePause(fltk::Button*, void*) {
  force_raw_stop();
}

fltk::Button* butTapeAuto;

static void cb_butTapeAuto(fltk::Button*, void*) {
  force_raw_auto();
}

fltk::Button* butTapeRewind;

static void cb_butTapeRewind(fltk::Button*, void*) {
  rewind_raw();
}

fltk::Slider* sldTape;

fltk::Button* butTapeRecord;

static void cb_butTapeRecord(fltk::Button*, void*) {
  force_raw_rec();
}

fltk::Button* butTapeErase;

static void cb_butTapeErase(fltk::Button*, void*) {
  tape_clear();
}

fltk::Output* txtoTapeAdjust;

fltk::Output* txtoTapeThresh;

fltk::Slider* sldTapeThresh;

static void cb_sldTapeThresh(fltk::Slider* o, void*) {
  char lbl[20];
    set_raw_thresh((int)o->value());
    txtoTapeThresh->value(itoa_mine((int)o->value(),lbl,16));
}

fltk::Slider* sldTapeAdjust;

static void cb_sldTapeAdjust(fltk::Slider* o, void*) {
  char lbl[20];
    set_tape_spd_adjust((int)o->value());
    txtoTapeAdjust->value(itoa_mine((int)o->value()-50,lbl,10));
}

fltk::Output* txtoMotor;

fltk::Output* txtoTapeCounter;

fltk::Button* butTapeMonitor;

static void cb_butTapeMonitor(fltk::Button*, void*) {
  set_show_tapemon(1);
}

fltk::CheckButton* chkSoundEnable;

static void cb_chkSoundEnable(fltk::CheckButton* o, void*) {
  set_SoundEnable(o->value());
}

fltk::Choice* chcDtype;

static void cb_chcDtype(fltk::Choice* o, void*) {
  set_d_mode(o->value());
}

fltk::Button* butLoadDisk;

static void cb_butLoadDisk(fltk::Button*, void*) {
  load_disk();
}

fltk::Button* butSaveDisk;

static void cb_butSaveDisk(fltk::Button*, void*) {
  save_disk();
}

fltk::Button* butLoadTape;

static void cb_butLoadTape(fltk::Button*, void*) {
  load_tape();
}

fltk::Button* butSaveDiksape;

static void cb_butSaveDiksape(fltk::Button*, void*) {
  save_tape();
}

fltk::Choice* chcDno;

static void cb_chcDno(fltk::Choice* o, void*) {
  set_d_num(o->value());
}

fltk::Output* txtoDoptions;

fltk::Output* txtoDepromenable;

fltk::Output* txtoDmotor;

fltk::Output* txtoDprecomp;

fltk::Output* txtoDsteprate;

fltk::Output* txtoDdrive;

fltk::Output* txtoDtrack;

fltk::Output* txtoDsector;

fltk::Output* txtoDcommand;

fltk::Output* txtoDdata;

fltk::Output* txtoDstatus;

fltk::Output* txtoDhead;

fltk::MultilineOutput* txtoDrivesize;

fltk::Output* txtoFPS;

static void cb_DTON(fltk::Button*, void*) {
  start_disk_trace();
}

static void cb_DTOFF(fltk::Button*, void*) {
  stop_disk_trace();
}

fltk::Window* statuswind;

fltk::Output* txtoStatusregs;

fltk::Output* txtoStatusStack;

fltk::Output* txtoStatus68451;

fltk::Output* txtoStatus68452;

fltk::Output* txtoStatusSound;

fltk::Button* butStatusClose;

static void cb_butStatusClose(fltk::Button*, void*) {
  chkStatus->value(0);
  statuswind->hide();
  show_status=0;
}

fltk::MultilineOutput* txtoDisas;

fltk::Button* butDisasPlus;

static void cb_butDisasPlus(fltk::Button*, void*) {
  char lbl[10];
  if(disas_bank<4)disas_bank++;
  sprintf(lbl,"%d",disas_bank);
  txtoDisasBank->value(lbl);
}

fltk::Button* butDisasMinus;

static void cb_butDisasMinus(fltk::Button*, void*) {
  char lbl[10];
  if(disas_bank>0)disas_bank--;
  sprintf(lbl,"%d",disas_bank);
  txtoDisasBank->value(lbl);
}

fltk::Output* txtoDisasBank;

fltk::Button* butStatusMore1;

static void cb_butStatusMore1(fltk::Button*, void*) {
  if(show_disas==0)
  {
  statuswind->resize((int)(statuswind->w()*1.3),(int)statuswind->h());
  show_disas=1;
  }
  else
  {
  statuswind->resize((int)(statuswind->w()/1.3),(int)statuswind->h());
  show_disas=0;
  }
;}

fltk::Group* grpVidlites4896;

fltk::Button* liteVID7_4896;

fltk::Button* liteVID6_4896;

fltk::Button* liteVID5_4896;

fltk::Button* liteVID4_4896;

fltk::Button* liteVID3_4896;

fltk::Button* liteVID2_4896;

fltk::Button* liteVID1_4896;

fltk::Button* liteVID0_4896;

fltk::InvisibleBox* txtVIDlites_4896;

fltk::Group* grpVidlites128;

fltk::Button* liteVID7_128;

fltk::Button* liteVID6_128;

fltk::Button* liteVID5_128;

fltk::Button* liteVID4_128;

fltk::Button* liteVID3_128;

fltk::Button* liteVID2_128;

fltk::Button* liteVID1_128;

fltk::Button* liteVID0_128;

fltk::InvisibleBox* txtVIDlites_128;

fltk::Button* butMemdump;

static void cb_butMemdump(fltk::Button*, void*) {
  save_memdump();
}

fltk::Group* grpBanklites4896;

fltk::Button* liteBANK7_4896;

fltk::Button* liteBANK6_4896;

fltk::Button* liteBANK5_4896;

fltk::Button* liteBANK4_4896;

fltk::Button* liteBANK3_4896;

fltk::Button* liteBANK2_4896;

fltk::Button* liteBANK1_4896;

fltk::Button* liteBANK0_4896;

fltk::InvisibleBox* txtBANKlites_4896;

fltk::Group* grpBanklites128;

fltk::Button* liteBANK7_128;

fltk::Button* liteBANK6_128;

fltk::Button* liteBANK5_128;

fltk::Button* liteBANK4_128;

fltk::Button* liteBANK3_128;

fltk::Button* liteBANK2_128;

fltk::Button* liteBANK1_128;

fltk::Button* liteBANK0_128;

fltk::InvisibleBox* txtBANKlites_128;

fltk::Output* txtoScanline;

fltk::Output* txtoPort84;

fltk::Output* txtoPort84timings;

fltk::Window* wndSysvars;

fltk::MultilineOutput* txtoSysvar1;

fltk::MultilineOutput* txtoSysvar2;

fltk::Window* wndMemScan;

fltk::MultilineOutput* txtoMemScan;

fltk::MultilineOutput* txtoMemScanAsc;

fltk::Input* txtiMemScanStart;

fltk::Button* butMemScanStartUpdate;

fltk::Button* butMemScanStartPlus;

static void cb_butMemScanStartPlus(fltk::Button*, void*) {
  set_memscan_start((memscan_start+0x100)%0xffff);
}

fltk::Button* butMemScanStartMinus;

static void cb_butMemScanStartMinus(fltk::Button*, void*) {
  set_memscan_start((memscan_start-0x100)%0xffff);
}

fltk::Button* butMemScanBank;

static void cb_butMemScanBank(fltk::Button*, void*) {
  memscan_bno++;
  if(memscan_bno>4)memscan_bno=0;
  set_memscan_bno(memscan_bno);
}

fltk::Output* txtoMemScanBank;

fltk::Input* txtiMemScanPokeAddr;

fltk::Input* txtiMemScanPokeData;

fltk::Button* butMemScanPoke;

fltk::Slider* sldMemScanPosit;

static void cb_sldMemScanPosit(fltk::Slider* o, void*) {
  set_memscan_start((int)(65280-o->value()));
}

fltk::Window* wndAbout;

fltk::Window* wndROMbuilder;

fltk::Choice* chcMachine;

static void cb_chcMachine(fltk::Choice* o, void*) {
  mach=o->value();
  update_ROMfiles();
}

fltk::Choice* chcROMHardware;

static void cb_chcROMHardware(fltk::Choice* o, void*) {
  romset_hwtypes[mach]=o->value();
  saveROMconfigfile()
;}

fltk::Button* rb0;

static void cb_rb0(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM0->value(filenam);
  strcpy(romset_files[mach*8+0],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb1;

static void cb_rb1(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM1->value(filenam);
  strcpy(romset_files[mach*8+1],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb2;

static void cb_rb2(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM2->value(filenam);
  strcpy(romset_files[mach*8+2],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb3;

static void cb_rb3(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM3->value(filenam);
  strcpy(romset_files[mach*8+3],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb4;

static void cb_rb4(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM4->value(filenam);
  strcpy(romset_files[mach*8+4],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb5;

static void cb_rb5(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM5->value(filenam);
  strcpy(romset_files[mach*8+5],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb6;

static void cb_rb6(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM6->value(filenam);
  strcpy(romset_files[mach*8+6],filenam);
  saveROMconfigfile();}
;}

fltk::Button* rb7;

static void cb_rb7(fltk::Button*, void*) {
  char *filenam;
  filenam=(char *)fltk::file_chooser("Load ROM", "*.rom", "*.rom", 0 );
  if(filenam!=NULL){txtoROM7->value(filenam);
  strcpy(romset_files[mach*8+7],filenam);
  saveROMconfigfile();}
;}

fltk::Button* butROMreset;

static void cb_butROMreset(fltk::Button*, void*) {
  init_ROMsets();
  saveROMconfigfile();
}

fltk::Button* butROMclose;

static void cb_butROMclose(fltk::Button*, void*) {
  wndROMbuilder->hide();
}

fltk::Output* txtoROM0;

fltk::Output* txtoROM2;

fltk::Output* txtoROM7;

fltk::Output* txtoROM3;

fltk::Output* txtoROM4;

fltk::Output* txtoROM5;

fltk::Output* txtoROM6;

fltk::Output* txtoROM1;

fltk::Button* xrb0;

static void cb_xrb0(fltk::Button*, void*) {
  txtoROM0->value("none");
  strcpy(romset_files[mach*8+0],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb1;

static void cb_xrb1(fltk::Button*, void*) {
  txtoROM1->value("none");
  strcpy(romset_files[mach*8+1],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb2;

static void cb_xrb2(fltk::Button*, void*) {
  txtoROM2->value("none");
  strcpy(romset_files[mach*8+2],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb3;

static void cb_xrb3(fltk::Button*, void*) {
  txtoROM3->value("none");
  strcpy(romset_files[mach*8+3],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb4;

static void cb_xrb4(fltk::Button*, void*) {
  txtoROM4->value("none");
  strcpy(romset_files[mach*8+4],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb5;

static void cb_xrb5(fltk::Button*, void*) {
  txtoROM5->value("none");
  strcpy(romset_files[mach*8+5],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb6;

static void cb_xrb6(fltk::Button*, void*) {
  txtoROM6->value("none");
  strcpy(romset_files[mach*8+6],"none");
  saveROMconfigfile()
;}

fltk::Button* xrb7;

static void cb_xrb7(fltk::Button*, void*) {
  txtoROM7->value("none");
  strcpy(romset_files[mach*8+7],"none");
  saveROMconfigfile()
;}

fltk::Window* make_window() {
  fltk::Window* w;
   {fltk::Window* o = mainwind = new fltk::Window(338, 659, "PALESDL Control Panel");
    o->set_vertical();
    o->begin();
     {fltk::Button* o = butMemscan = new fltk::Button(0, 115, 65, 25, "MemScan");
      o->callback((fltk::Callback*)cb_butMemscan);
    }
    butCPM = new fltk::Button(65, 115, 65, 25, "CPM");
    new fltk::Button(130, 115, 65, 25, "Printer");
    new fltk::Button(0, 140, 65, 25, "Z80-TAP");
     {fltk::Button* o = butStopemu = new fltk::Button(65, 320, 65, 25, "@square");
      o->callback((fltk::Callback*)cb_butStopemu);
    }
     {fltk::Button* o = butReset = new fltk::Button(5, 320, 55, 55, "X");
      o->callback((fltk::Callback*)cb_butReset);
    }
     {fltk::Button* o = butROMbuilder = new fltk::Button(130, 140, 65, 25, "ROM Edit");
      o->callback((fltk::Callback*)cb_butROMbuilder);
    }
    new fltk::Button(65, 140, 65, 25, "TapeRead");
     {fltk::Button* o = butExit = new fltk::Button(205, 345, 130, 60, "Exit");
      o->callback((fltk::Callback*)cb_butExit);
    }
    butControlMore = new fltk::Button(5, 380, 55, 25, "More");
     {fltk::Button* o = butHelp = new fltk::Button(65, 380, 125, 25, "Help");
      o->callback((fltk::Callback*)cb_butHelp);
    }
     {fltk::Button* o = butStartemu = new fltk::Button(135, 320, 55, 55, "@>");
      o->callback((fltk::Callback*)cb_butStartemu);
    }
     {fltk::Button* o = butSSemu = new fltk::Button(65, 350, 65, 25, "S.Step");
      o->callback((fltk::Callback*)cb_butSSemu);
    }
     {fltk::Button* o = butRunprogram = new fltk::Button(225, 280, 95, 60, "RUN");
      o->callback((fltk::Callback*)cb_butRunprogram);
    }
     {fltk::Choice* o = chcLanguage = new fltk::Choice(60, 170, 95, 25, "Language");
      o->add("English");
      o->add("Francais");
    }
     {fltk::Choice* o = chcSpeed = new fltk::Choice(60, 200, 95, 25, "Speed");
      o->callback((fltk::Callback*)cb_chcSpeed);
      o->add("25%");
      o->add("50%");
      o->add("100%");
      o->add("200%");
      o->add("400%");
      o->add("800%");
      o->add("1000%");
      o->add("Ninja (2K)");
      o->add("WOW (5K)");
      o->add("32K");
    }
     {fltk::Choice* o = chcMtype = new fltk::Choice(60, 230, 95, 25, "Type");
      o->callback((fltk::Callback*)cb_chcMtype);
      o->add("48K");
      o->add("96K");
      o->add("128K");
      o->add("96K Disk");
      o->add("128K Disk");
      o->add("USER1");
      o->add("USER2");
    }
     {fltk::Choice* o = chcDisplay = new fltk::Choice(60, 260, 95, 25, "Display");
      o->callback((fltk::Callback*)cb_chcDisplay);
      o->add("Custom");
      o->add("1x (Fast)");
      o->add("2x");
    }
    butDisplayReset = new fltk::Button(160, 260, 25, 25, "x");
     {fltk::Button* o = new fltk::Button(0, 0, 195, 110, " ");
      o->color((fltk::Color)56);
      o->deactivate();
    }
     {fltk::InvisibleBox* o = new fltk::InvisibleBox(40, 20, 20, 15, "PALE SDL");
      o->color((fltk::Color)0xffffff00);
      o->buttoncolor((fltk::Color)0xffffff00);
      o->labelcolor((fltk::Color)0xffffff00);
      o->highlight_color((fltk::Color)0xffffff00);
      o->labelsize(18);
    }
     {fltk::CheckButton* o = chkSysvars = new fltk::CheckButton(110, 60, 65, 25, "SysVars");
      o->labelcolor((fltk::Color)0xffffff00);
      o->callback((fltk::Callback*)cb_chkSysvars);
    }
     {fltk::CheckButton* o = chkMemmap = new fltk::CheckButton(5, 60, 90, 25, "Memory Map");
      o->labelcolor((fltk::Color)0xffffff00);
      o->callback((fltk::Callback*)cb_chkMemmap);
    }
     {fltk::CheckButton* o = chkStatus = new fltk::CheckButton(5, 85, 100, 25, "Status Display");
      o->labelcolor((fltk::Color)0xffffff00);
      o->callback((fltk::Callback*)cb_chkStatus);
    }
    divNumber1 = new fltk::Divider();
     {fltk::MultilineOutput* o = txtoTapeInfo = new fltk::MultilineOutput(200, 25, 135, 120, "Tape Info");
      o->type(4);
      o->color((fltk::Color)0xb8b8b800);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      o->value("");
    }
     {fltk::Button* o = new fltk::Button(145, 31, 10, 10, " ");
      o->set_vertical();
      o->buttoncolor((fltk::Color)0xff000900);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(153, 19, 10, 10, " ");
      o->buttoncolor((fltk::Color)0xfff71e00);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(165, 17, 10, 10, " ");
      o->buttoncolor((fltk::Color)0xff7b4700);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(177, 25, 10, 10, " ");
      o->set_vertical();
      o->buttoncolor((fltk::Color)0x10ff0800);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(157, 37, 18, 18, " ");
      o->set_vertical();
      o->buttoncolor((fltk::Color)0x3f54ff00);
      o->deactivate();
    }
     {fltk::Output* o = txtoRevisions = new fltk::Output(10, 35, 100, 25, " ");
      o->box(fltk::NO_BOX);
      o->buttonbox(fltk::NO_BOX);
      o->color((fltk::Color)56);
      o->textcolor((fltk::Color)0xffffff00);
      o->labelsize(14);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(275, 0, 60, 25, "LIST");
      o->callback((fltk::Callback*)cb_LIST);
    }
     {fltk::Choice* o = chcTtype = new fltk::Choice(240, 155, 95, 25, "Tape");
      o->callback((fltk::Callback*)cb_chcTtype);
      o->add("TAP Files");
      o->add("LSF Files");
      o->add("Level9 Files");
      o->add("RAW Files");
      o->add("WAV Files");
    }
     {fltk::Group* o = grpTapeDirect = new fltk::Group(0, 410, 330, 125);
      o->begin();
       {fltk::Button* o = butTapePlay = new fltk::Button(90, 55, 35, 30, ">");
        o->labelsize(24);
        o->callback((fltk::Callback*)cb_butTapePlay);
      }
       {fltk::Button* o = butTapePause = new fltk::Button(55, 75, 35, 30, "II");
        o->labelsize(24);
        o->callback((fltk::Callback*)cb_butTapePause);
      }
       {fltk::Button* o = butTapeAuto = new fltk::Button(55, 55, 35, 20, "auto");
        o->callback((fltk::Callback*)cb_butTapeAuto);
      }
       {fltk::Button* o = butTapeRewind = new fltk::Button(20, 55, 35, 30, "<<");
        o->labelsize(24);
        o->callback((fltk::Callback*)cb_butTapeRewind);
      }
       {fltk::Slider* o = sldTape = new fltk::Slider(10, 30, 320, 15);
        o->maximum(32768);
        o->step(100);
      }
       {fltk::Button* o = butTapeRecord = new fltk::Button(130, 55, 25, 30, "R");
        o->set_vertical();
        o->callback((fltk::Callback*)cb_butTapeRecord);
      }
       {fltk::Button* o = butTapeErase = new fltk::Button(160, 55, 40, 30, "Erase");
        o->callback((fltk::Callback*)cb_butTapeErase);
      }
       {fltk::Output* o = txtoTapeAdjust = new fltk::Output(225, 60, 25, 25, " ");
        o->value("0");
      }
       {fltk::Output* o = txtoTapeThresh = new fltk::Output(225, 90, 25, 25, " ");
        o->value("70");
      }
       {fltk::Slider* o = sldTapeThresh = new fltk::Slider(255, 100, 75, 15, "Threshold");
        o->minimum(8);
        o->maximum(248);
        o->value(128);
        o->callback((fltk::Callback*)cb_sldTapeThresh);
        o->align(fltk::ALIGN_TOP);
      }
       {fltk::Slider* o = sldTapeAdjust = new fltk::Slider(255, 65, 75, 15, "Speed Adj.");
        o->maximum(100);
        o->value(50);
        o->callback((fltk::Callback*)cb_sldTapeAdjust);
        o->align(fltk::ALIGN_TOP);
      }
       {fltk::Output* o = txtoMotor = new fltk::Output(205, 0, 30, 20, "Motor");
        o->color((fltk::Color)0x4cdfff00);
        o->value("OFF");
      }
       {fltk::Output* o = txtoTapeCounter = new fltk::Output(240, 0, 90, 20, " ");
        o->value("0");
      }
       {fltk::Button* o = butTapeMonitor = new fltk::Button(95, 95, 60, 20, "Monitor");
        o->callback((fltk::Callback*)cb_butTapeMonitor);
      }
      o->end();
    }
     {fltk::CheckButton* o = chkSoundEnable = new fltk::CheckButton(130, 285, 65, 25, "Sound");
      o->callback((fltk::Callback*)cb_chkSoundEnable);
    }
     {fltk::Choice* o = chcDtype = new fltk::Choice(255, 215, 80, 25, "Type");
      o->callback((fltk::Callback*)cb_chcDtype);
      o->add("LDF Files");
      o->add("DSK Files");
      o->add("YAZE Files");
      o->add("Real Disks");
    }
     {fltk::Button* o = butLoadDisk = new fltk::Button(195, 245, 70, 25, "Load");
      o->callback((fltk::Callback*)cb_butLoadDisk);
    }
     {fltk::Button* o = butSaveDisk = new fltk::Button(265, 245, 70, 25, "Save");
      o->callback((fltk::Callback*)cb_butSaveDisk);
    }
     {fltk::Button* o = butLoadTape = new fltk::Button(195, 185, 70, 25, "Load");
      o->callback((fltk::Callback*)cb_butLoadTape);
    }
     {fltk::Button* o = butSaveDiksape = new fltk::Button(265, 185, 70, 25, "Save");
      o->callback((fltk::Callback*)cb_butSaveDiksape);
    }
    new fltk::InvisibleBox(45, 285, 25, 25, "F7/F8=Fullscreen");
     {fltk::Choice* o = chcDno = new fltk::Choice(190, 215, 35, 25, "Disk");
      o->callback((fltk::Callback*)cb_chcDno);
      o->add("A");
      o->add("B");
      o->add("C");
      o->add("D");
    }
     {fltk::Output* o = txtoDoptions = new fltk::Output(200, 530, 50, 25, "Options");
      o->value("");
    }
     {fltk::Output* o = txtoDepromenable = new fltk::Output(200, 555, 50, 25, "Eprom");
      o->value("");
    }
     {fltk::Output* o = txtoDmotor = new fltk::Output(200, 580, 50, 25, "Motor");
      o->value("");
    }
     {fltk::Output* o = txtoDprecomp = new fltk::Output(200, 605, 50, 25, "PreComp");
      o->value("");
    }
     {fltk::Output* o = txtoDsteprate = new fltk::Output(200, 630, 50, 25, "StepRate");
      o->value("");
    }
     {fltk::Output* o = txtoDdrive = new fltk::Output(255, 535, 25, 25, "Drive");
      o->align(fltk::ALIGN_RIGHT);
      o->value("");
    }
     {fltk::Output* o = txtoDtrack = new fltk::Output(255, 585, 25, 25, "Track");
      o->align(fltk::ALIGN_RIGHT);
      o->value("");
    }
     {fltk::Output* o = txtoDsector = new fltk::Output(255, 615, 25, 25, "Sector");
      o->align(fltk::ALIGN_RIGHT);
      o->value("");
    }
     {fltk::Output* o = txtoDcommand = new fltk::Output(85, 540, 25, 25, "Command");
      o->value("");
    }
     {fltk::Output* o = txtoDdata = new fltk::Output(85, 565, 25, 25, "Data");
      o->value("");
    }
     {fltk::Output* o = txtoDstatus = new fltk::Output(85, 590, 25, 25, "Status");
      o->value("");
    }
     {fltk::Output* o = txtoDhead = new fltk::Output(255, 560, 25, 25, "Head");
      o->align(fltk::ALIGN_RIGHT);
      o->value("");
    }
     {fltk::MultilineOutput* o = txtoDrivesize = new fltk::MultilineOutput(15, 630, 120, 25, "A:     B:     C:     D:");
      o->type(4);
      o->align(fltk::ALIGN_TOP);
      o->value("");
    }
     {fltk::Output* o = txtoFPS = new fltk::Output(155, 85, 30, 20, "FPS:");
      o->selection_color((fltk::Color)0xffffff00);
      o->selection_textcolor((fltk::Color)56);
      o->labelcolor((fltk::Color)0xffffff00);
    }
     {fltk::Button* o = new fltk::Button(5, 520, 45, 20, "DTON");
      o->callback((fltk::Callback*)cb_DTON);
      o->deactivate();
    }
     {fltk::Button* o = new fltk::Button(55, 520, 35, 20, "DTOFF");
      o->callback((fltk::Callback*)cb_DTOFF);
      o->deactivate();
    }
    o->end();
  }
   {fltk::Window* o = statuswind = new fltk::Window(610, 369, "PALE Status");
    o->begin();
    new fltk::Button(5, 305, 55, 20, "dev stuff");
     {fltk::Output* o = txtoStatusregs = new fltk::Output(0, 190, 410, 20, "Z80 Registers");
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
     {fltk::Output* o = txtoStatusStack = new fltk::Output(0, 225, 410, 20, "Z80 Stack");
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
     {fltk::Output* o = txtoStatus68451 = new fltk::Output(0, 260, 455, 20, " 6845 Registers");
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
    txtoStatus68452 = new fltk::Output(0, 280, 455, 20, " ");
    txtoStatusSound = new fltk::Output(145, 305, 235, 20, "Sound Status");
     {fltk::Button* o = butStatusClose = new fltk::Button(385, 305, 80, 25, "Close");
      o->callback((fltk::Callback*)cb_butStatusClose);
    }
     {fltk::MultilineOutput* o = txtoDisas = new fltk::MultilineOutput(470, 0, 140, 310, " ");
      o->type(4);
      o->set_vertical();
    }
     {fltk::Button* o = butDisasPlus = new fltk::Button(525, 310, 45, 20, "Bank +");
      o->callback((fltk::Callback*)cb_butDisasPlus);
    }
     {fltk::Button* o = butDisasMinus = new fltk::Button(475, 310, 45, 20, "Bank -");
      o->callback((fltk::Callback*)cb_butDisasMinus);
    }
     {fltk::Output* o = txtoDisasBank = new fltk::Output(575, 310, 35, 20, " ");
      o->deactivate();
      o->value("0");
    }
     {fltk::Button* o = butStatusMore1 = new fltk::Button(435, 5, 25, 145, ">");
      o->set_vertical();
      o->callback((fltk::Callback*)cb_butStatusMore1);
    }
     {fltk::Group* o = grpVidlites4896 = new fltk::Group(15, 5, 185, 165);
      o->begin();
       {fltk::Button* o = liteVID7_4896 = new fltk::Button(15, 30, 10, 10, "Frame Blanking");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID6_4896 = new fltk::Button(15, 45, 10, 10, "Line Blank Mono");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID5_4896 = new fltk::Button(15, 60, 10, 10, "CPU Access");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID4_4896 = new fltk::Button(15, 75, 10, 10, "Alt Green Select");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID3_4896 = new fltk::Button(15, 90, 10, 10, "Bank 3 / CASEN");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID2_4896 = new fltk::Button(15, 105, 10, 10, "Bank2 /CASEN");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID1_4896 = new fltk::Button(15, 120, 10, 10, "Cass Motor Enable");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID0_4896 = new fltk::Button(15, 135, 10, 10, "Speaker Enable");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::InvisibleBox* o = txtVIDlites_4896 = new fltk::InvisibleBox(130, 75, 25, 25, "00");
        o->labelsize(16);
      }
       {fltk::InvisibleBox* o = new fltk::InvisibleBox(85, 5, 25, 25, "VIDEO LATCH (0x80)");
        o->labelsize(14);
      }
      o->end();
    }
     {fltk::Group* o = grpVidlites128 = new fltk::Group(10, -5, 185, 165);
      o->hide();
      o->begin();
       {fltk::Button* o = liteVID7_128 = new fltk::Button(25, 40, 10, 10, "Serial Data Out");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID6_128 = new fltk::Button(25, 55, 10, 10, "Line Blank Mono");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID5_128 = new fltk::Button(25, 70, 10, 10, "CPU Access");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID4_128 = new fltk::Button(25, 85, 10, 10, "Alt Green Select");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID3_128 = new fltk::Button(25, 100, 10, 10, "CAS Motor Enable");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID2_128 = new fltk::Button(25, 115, 10, 10, "CAS Enable");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID1_128 = new fltk::Button(25, 130, 10, 10, "Serial HS Out");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteVID0_128 = new fltk::Button(25, 145, 10, 10, "Speaker Enable");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::InvisibleBox* o = txtVIDlites_128 = new fltk::InvisibleBox(140, 85, 25, 25, "00");
        o->labelsize(16);
      }
       {fltk::InvisibleBox* o = new fltk::InvisibleBox(95, 15, 25, 25, "VIDEO LATCH (0x80)");
        o->labelsize(14);
      }
      o->end();
    }
     {fltk::Button* o = butMemdump = new fltk::Button(220, 170, 85, 20, "MemDump");
      o->callback((fltk::Callback*)cb_butMemdump);
    }
     {fltk::Group* o = grpBanklites4896 = new fltk::Group(215, -5, 185, 165);
      o->begin();
       {fltk::Button* o = liteBANK7_4896 = new fltk::Button(25, 40, 10, 10, "RDEN4");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK6_4896 = new fltk::Button(25, 55, 10, 10, "RDEN 2/3");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK5_4896 = new fltk::Button(25, 70, 10, 10, "/RDEN1");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK4_4896 = new fltk::Button(25, 85, 10, 10, "/RDEN0");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK3_4896 = new fltk::Button(25, 100, 10, 10, "WREN4");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK2_4896 = new fltk::Button(25, 115, 10, 10, "WREN3");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK1_4896 = new fltk::Button(25, 130, 10, 10, "WREN2");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK0_4896 = new fltk::Button(25, 145, 10, 10, "/WREN1");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::InvisibleBox* o = txtBANKlites_4896 = new fltk::InvisibleBox(140, 85, 25, 25, "00");
        o->labelsize(16);
      }
       {fltk::InvisibleBox* o = new fltk::InvisibleBox(95, 15, 25, 25, "BANK LATCH (0x7F)");
        o->labelsize(14);
      }
      o->end();
    }
     {fltk::Group* o = grpBanklites128 = new fltk::Group(205, -15, 185, 165);
      o->hide();
      o->begin();
       {fltk::Button* o = liteBANK7_128 = new fltk::Button(35, 50, 10, 10, "/WREN1");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK6_128 = new fltk::Button(35, 65, 10, 10, "WREN2");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK5_128 = new fltk::Button(35, 80, 10, 10, "COLSEL");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK4_128 = new fltk::Button(35, 95, 10, 10, "WREN4");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK3_128 = new fltk::Button(35, 110, 10, 10, "/RDEN0");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK2_128 = new fltk::Button(35, 125, 10, 10, "/RDEN1");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK1_128 = new fltk::Button(35, 140, 10, 10, "RDEN2");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::Button* o = liteBANK0_128 = new fltk::Button(35, 155, 10, 10, "RDEN4");
        o->box(fltk::UP_BOX);
        o->buttoncolor((fltk::Color)56);
        o->highlight_color((fltk::Color)56);
        o->align(fltk::ALIGN_RIGHT);
      }
       {fltk::InvisibleBox* o = txtBANKlites_128 = new fltk::InvisibleBox(150, 95, 25, 25, "00");
        o->labelsize(16);
      }
       {fltk::InvisibleBox* o = new fltk::InvisibleBox(105, 25, 25, 25, "BANK LATCH (0x82)");
        o->labelsize(14);
      }
      o->end();
    }
    txtoScanline = new fltk::Output(360, 170, 45, 20, "Scanline");
    txtoPort84 = new fltk::Output(45, 330, 420, 20, "Port84");
    txtoPort84timings = new fltk::Output(45, 350, 420, 20, "Timing");
    o->end();
  }
   {fltk::Window* o = wndSysvars = new fltk::Window(260, 474, "SysTem vArIAbLeS");
    o->begin();
     {fltk::MultilineOutput* o = txtoSysvar1 = new fltk::MultilineOutput(0, 5, 130, 470, " ");
      o->type(4);
      o->set_vertical();
    }
     {fltk::MultilineOutput* o = txtoSysvar2 = new fltk::MultilineOutput(130, 5, 130, 470, " ");
      o->type(4);
      o->set_vertical();
    }
    o->end();
  }
   {fltk::Window* o = wndMemScan = new fltk::Window(436, 620, "Memory Scanner");
    o->begin();
     {fltk::MultilineOutput* o = txtoMemScan = new fltk::MultilineOutput(0, 0, 295, 550, " ");
      o->type(4);
      o->set_vertical();
      o->textfont(fltk::COURIER);
      o->textsize(15);
    }
     {fltk::MultilineOutput* o = txtoMemScanAsc = new fltk::MultilineOutput(295, 0, 110, 550, " ");
      o->type(4);
      o->set_vertical();
      o->textfont(fltk::COURIER);
      o->textsize(15);
    }
     {fltk::Input* o = txtiMemScanStart = new fltk::Input(60, 560, 50, 25, "Start");
      o->value("0");
    }
     {fltk::Button* o = butMemScanStartUpdate = new fltk::Button(115, 560, 20, 25, "U");
      o->set_vertical();
    }
     {fltk::Button* o = butMemScanStartPlus = new fltk::Button(170, 560, 25, 25, "+");
      o->callback((fltk::Callback*)cb_butMemScanStartPlus);
    }
     {fltk::Button* o = butMemScanStartMinus = new fltk::Button(145, 560, 25, 25, "-");
      o->callback((fltk::Callback*)cb_butMemScanStartMinus);
    }
     {fltk::Button* o = butMemScanBank = new fltk::Button(35, 590, 40, 25, "Bank");
      o->callback((fltk::Callback*)cb_butMemScanBank);
    }
     {fltk::Output* o = txtoMemScanBank = new fltk::Output(80, 590, 25, 25, " ");
      o->value("0");
    }
     {fltk::Input* o = txtiMemScanPokeAddr = new fltk::Input(225, 560, 50, 25, "=");
      o->align(fltk::ALIGN_RIGHT);
      o->value("0");
    }
     {fltk::Input* o = txtiMemScanPokeData = new fltk::Input(290, 560, 30, 25, " ");
      o->align(fltk::ALIGN_RIGHT);
      o->value("0");
    }
    butMemScanPoke = new fltk::Button(325, 560, 40, 25, "Poke");
     {fltk::Slider* o = sldMemScanPosit = new fltk::Slider(410, 0, 25, 550);
      o->set_vertical();
      o->maximum(65280);
      o->step(8);
      o->linesize(0);
      o->value(65280);
      o->callback((fltk::Callback*)cb_sldMemScanPosit);
    }
    new fltk::InvisibleBox(250, 590, 25, 25, "You Must Stop the Emulator to change Start");
    o->end();
  }
   {fltk::Window* o = wndAbout = new fltk::Window(205, 247, "About PALE SDL");
    o->color((fltk::Color)0xffffff00);
    o->begin();
     {fltk::Button* o = new fltk::Button(5, 10, 195, 110, " ");
      o->color((fltk::Color)56);
      o->deactivate();
    }
     {fltk::InvisibleBox* o = new fltk::InvisibleBox(90, 60, 20, 15, "PALE SDL");
      o->color((fltk::Color)0xffffff00);
      o->buttoncolor((fltk::Color)0xffffff00);
      o->labelcolor((fltk::Color)0xffffff00);
      o->highlight_color((fltk::Color)0xffffff00);
      o->labelsize(18);
    }
    new fltk::InvisibleBox(85, 140, 25, 25, "Emulator Programming");
    new fltk::InvisibleBox(85, 160, 25, 25, "Pete Todd");
    new fltk::InvisibleBox(90, 190, 25, 25, "Z80 Core");
    new fltk::InvisibleBox(85, 210, 25, 25, "RAZE - Richard Mitton");
    o->end();
  }
   {fltk::Window* o = wndROMbuilder = new fltk::Window(458, 285, "ROM Builder");
    w = o;
    o->begin();
     {fltk::Choice* o = chcMachine = new fltk::Choice(140, 5, 110, 25, "Machine:");
      o->callback((fltk::Callback*)cb_chcMachine);
      o->add("48K");
      o->add("96K");
      o->add("128K");
      o->add("96K Disk");
      o->add("128K Disk");
      o->add("USER1");
      o->add("USER2");
    }
     {fltk::Choice* o = chcROMHardware = new fltk::Choice(325, 5, 120, 25, "Hardware:");
      o->callback((fltk::Callback*)cb_chcROMHardware);
      o->add("48K");
      o->add("96K");
      o->add("128K");
      o->add("SpeccyHack");
      o->add("Jasper");
    }
     {fltk::Button* o = rb0 = new fltk::Button(10, 40, 75, 20, "0000-1FFF");
      o->callback((fltk::Callback*)cb_rb0);
    }
     {fltk::Button* o = rb1 = new fltk::Button(10, 65, 75, 20, "2000-3FFF");
      o->callback((fltk::Callback*)cb_rb1);
    }
     {fltk::Button* o = rb2 = new fltk::Button(10, 90, 75, 20, "4000-5FFF");
      o->callback((fltk::Callback*)cb_rb2);
    }
     {fltk::Button* o = rb3 = new fltk::Button(10, 115, 75, 20, "6000-7FFF");
      o->callback((fltk::Callback*)cb_rb3);
    }
     {fltk::Button* o = rb4 = new fltk::Button(10, 140, 75, 20, "8000-9FFF");
      o->callback((fltk::Callback*)cb_rb4);
    }
     {fltk::Button* o = rb5 = new fltk::Button(10, 165, 75, 20, "A000-BFFF");
      o->callback((fltk::Callback*)cb_rb5);
    }
     {fltk::Button* o = rb6 = new fltk::Button(10, 190, 75, 20, "C000-DFFF");
      o->callback((fltk::Callback*)cb_rb6);
    }
     {fltk::Button* o = rb7 = new fltk::Button(10, 215, 75, 20, "E000-FFFF");
      o->callback((fltk::Callback*)cb_rb7);
    }
     {fltk::Button* o = butROMreset = new fltk::Button(15, 250, 150, 25, "Reset Archive to defaults");
      o->callback((fltk::Callback*)cb_butROMreset);
    }
     {fltk::Button* o = butROMclose = new fltk::Button(245, 245, 110, 35, "Close");
      o->callback((fltk::Callback*)cb_butROMclose);
    }
    txtoROM0 = new fltk::Output(115, 40, 335, 20, " ");
    txtoROM2 = new fltk::Output(115, 90, 335, 20, " ");
    txtoROM7 = new fltk::Output(115, 215, 335, 20, " ");
    txtoROM3 = new fltk::Output(115, 115, 335, 20, " ");
    txtoROM4 = new fltk::Output(115, 140, 335, 20, " ");
    txtoROM5 = new fltk::Output(115, 165, 335, 20, " ");
    txtoROM6 = new fltk::Output(115, 190, 335, 20, " ");
    txtoROM1 = new fltk::Output(115, 65, 335, 20, " ");
     {fltk::Button* o = xrb0 = new fltk::Button(90, 40, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb0);
    }
     {fltk::Button* o = xrb1 = new fltk::Button(90, 65, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb1);
    }
     {fltk::Button* o = xrb2 = new fltk::Button(90, 90, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb2);
    }
     {fltk::Button* o = xrb3 = new fltk::Button(90, 115, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb3);
    }
     {fltk::Button* o = xrb4 = new fltk::Button(90, 140, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb4);
    }
     {fltk::Button* o = xrb5 = new fltk::Button(90, 165, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb5);
    }
     {fltk::Button* o = xrb6 = new fltk::Button(90, 190, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb6);
    }
     {fltk::Button* o = xrb7 = new fltk::Button(90, 215, 20, 20, "X");
      o->callback((fltk::Callback*)cb_xrb7);
    }
    o->end();
    update_ROMfiles();
  }
  return  w;
}
